name: Asset on boarding request
description: to add a new asset
labels: [kind/request]

body:
  - type: markdown
    attributes:
      value: |
        ### Submit a new Asset onboarding request
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the application
      description: A clear and concise description of what the bug is.
      placeholder: Describe the application
    validations:
      required: true
  - type: textarea
    id: gitrepo
    attributes:
      label: GIT repo
      description: mention the gitrepo
      placeholder: |
       Provide GIT URL
    validations:
      required: true

 
